# Generated by Django 5.1.7 on 2025-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_planmembresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, help_text='Ej: Cardio, Pesas, Funcional, etc.', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('MTTO', 'En mantenimiento'), ('FUERA', 'Fuera de servicio')], default='DISP', max_length=5)),
                ('fecha_ultima_revision', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
