# Generated by Django 5.1.7 on 2025-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
