# Generated by Django 5.1.7 on 2025-03-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0004_equipo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmembresia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes_membresia/'),
        ),
    ]
