# Generated by Django 5.1.7 on 2025-03-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0005_planmembresia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.TimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo del Usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
