# Generated by Django 5.1.7 on 2025-03-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0007_clasegrupal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasegrupal',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Entrenador encargado de la clase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion1.usuario'),
        ),
    ]
