# Generated by Django 5.1.7 on 2025-04-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0010_inscripcionclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la sesión')),
                ('hora', models.TimeField(help_text='Hora de inicio de la sesión')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_personalizadas', to='Aplicacion1.usuario')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_entrenadas', to='Aplicacion1.usuario')),
            ],
        ),
    ]
