# Generated by Django 5.1.7 on 2025-04-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0011_sesionpersonalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.planmembresia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.usuario')),
            ],
        ),
    ]
