# Generated by Django 5.1.7 on 2025-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0012_compraplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmembresia',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
