[phases.setup]
nixPkgs = ["python312"]

[phases.build]
cmds = ["python3 -m pip install -r requirements.txt", "python3 manage.py migrate", "python3 manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn Proyecto.wsgi:application --bind 0.0.0.0:$PORT"